version: '3'

services:
  dev:
    image: shaunwhitely/mypart-dependencies@sha256:eb852cd03601dc6da7d0bf670c0334b44dfb96bb1d0dbdf65afb1bae6ed2501c
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: support/dev/entrypoint
    command: /bin/bash
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ''
      DB_DATABASE: devdb
      DB_TABLE: devtable
      DB_COLUMN: devcolumn
    depends_on:
      - database
  database:
    build: support/database
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
