name:                mypart
version:             0.1.0.0
github:              "shaun-whitely/mypart"
license:             BSD3
author:              "Shaun Whitely"
maintainer:          "38450416+shaun-whitely@users.noreply.github.com"
copyright:           "2020 Shaun Whitely"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shaun-whitely/mypart#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - mysql-simple
  - split
  - text
  - time

default-extensions:
  - FlexibleContexts
  - OverloadedStrings
  - ScopedTypeVariables
  - TypeApplications

library:
  source-dirs: src

executables:
  mypart-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mypart

tests:
  mypart-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mypart
      - hspec
      - hedgehog
      - hedgehog-classes
