name: Pull Request CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Test
        run: auto/test
